### ISSUE TITLE
Слова с дефисом перед "="

### ISSUE THREAD

**Issue by solanum-tuberosum** [timarkh/uniparser-grammar-meadow-mari#8]
Мб сделать так, чтобы слово с дефисом перед "=" полностью не разбиралось? Ср. Мари-Турекышк=
![image](https://user-images.githubusercontent.com/13102259/109126993-f66e7f80-775e-11eb-87bd-a3237bd6610d.png)

**Comment by timarkh** [comment]
Вроде поправил. (И это тоже не про парсер.:)
