### ISSUE TITLE
аннотации на аннотациях?

### ISSUE THREAD

**Issue by solanum-tuberosum** [timarkh/uniparser-grammar-meadow-mari#9]
Кажется, здесь что-то не так... Файл biografia 1
![image](https://user-images.githubusercontent.com/13102259/109130472-d345cf00-7762-11eb-87ce-0ee98ef224de.png)

**Comment by timarkh** [comment]
А это потому что в исходном файле у двух разных говорящих было указано Participant=SPEAKER, а должно было быть два разных идентификатора. Конвертор решил, что это один и тот же говорящий, и слил разборы к двум накладывающимся репликам в один слой. Сейчас попросим Айгуль поправить это во всех файлах. (Но это тоже не про парсер!:)
